# Generated by Django 5.0.1 on 2024-02-03 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('photo_main', models.ImageField(upload_to='photo/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('event_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
