# Generated by Django 5.0.1 on 2024-02-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='event',
            name='photo_5',
        ),
        migrations.AlterField(
            model_name='event',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='', verbose_name='photo/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='', verbose_name='photo/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='', verbose_name='photo/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo_main',
            field=models.ImageField(upload_to='photo/<django.db.models.fields.CharField>/'),
        ),
    ]
