# Generated by Django 5.0.1 on 2024-02-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_photo_4_remove_event_photo_5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photo/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photo/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='photo/<django.db.models.fields.CharField>/'),
        ),
    ]
