# Generated by Django 5.0.1 on 2024-02-03 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=200)),
                ('event_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('participated_date', models.DateField(default=datetime.datetime.now)),
                ('user_id', models.IntegerField(blank=True)),
                ('p_photo', models.ImageField(upload_to='', verbose_name='<django.db.models.fields.CharField>photo')),
            ],
        ),
    ]
