# Generated by Django 5.0.1 on 2024-02-03 18:30

import participant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='p_photo',
            field=models.ImageField(upload_to=participant.models.user_directory_path),
        ),
    ]
