# Generated by Django 5.0.2 on 2024-02-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_alter_participant_p_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='message',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='phone',
        ),
    ]
